# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  -
    env:
      - CGO_ENABLED=0
    binary: docker-machine-driver-linode
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .Binary }}_{{ .Os }}-{{ .Arch }}"
  format: zip
# replacements:
#    darwin: Darwin
#    linux: Linux
#    windows: Windows
#    386: i386
#    amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
