name: build

on:
  workflow_dispatch: null
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - run: go version

      - name: Build binary
        run: make